/**
 * Shared Bearer Token Auth Middleware
 * 
 * Token resolution order:
 * 1. Environment variable: ICE_AUTH_TOKEN
 * 2. Fallback config value
 * 3. Auto-generated random token (if none configured)
 * 
 * Auth is always enforced by default. In FRP TCP forwarding scenarios,
 * all external requests appear as localhost (127.0.0.1), so IP-based
 * exemption is NOT safe. Use `auth.skipLocalhost: true` in config.json
 * ONLY for local development convenience.
 */

import { randomBytes } from 'crypto';
import { readFileSync, writeFileSync, existsSync } from 'fs';
import { join } from 'path';
import type { Request, Response, NextFunction } from 'express';

export interface AuthMiddlewareConfig {
    token?: string;
    /** If true, skip auth for localhost requests (ONLY for local dev, NOT for FRP deployments) */
    skipLocalhost?: boolean;
}

/**
 * Generate a random hex token
 */
function generateToken(): string {
    return randomBytes(24).toString('hex');
}

/**
 * Check if the request originates from localhost
 */
function isLocalhost(req: Request): boolean {
    const ip = req.ip || req.socket.remoteAddress || '';
    return ip === '127.0.0.1' || ip === '::1' || ip === '::ffff:127.0.0.1' || ip === 'localhost';
}

/**
 * Track whether the current token was auto-generated (vs user-configured).
 */
let isAutoGenerated = false;

/**
 * Save the generated token to config.json (best-effort).
 */
function saveTokenToConfig(token: string): void {
    const configPath = join(process.cwd(), 'config', 'config.json');
    try {
        if (!existsSync(configPath)) {
            console.log(`[AUTH] Config file not found at ${configPath}, cannot persist token`);
            return;
        }
        const raw = readFileSync(configPath, 'utf-8');
        const config = JSON.parse(raw);
        if (!config.auth) config.auth = {};
        if (config.auth.token === token) return; // already saved
        config.auth.token = token;
        writeFileSync(configPath, JSON.stringify(config, null, 2) + '\n', 'utf-8');
        console.log(`[AUTH] Token persisted to config.json`);
    } catch (err) {
        console.log(`[AUTH] Failed to persist token to config.json: ${err instanceof Error ? err.message : String(err)}`);
    }
}

/**
 * Get auth token from environment variable, fallback to config.
 * If none configured, auto-generate, log a warning, and persist to config.json.
 */
export function getAuthToken(configToken?: string): string {
    const envToken = process.env.ICE_AUTH_TOKEN || configToken || '';
    if (envToken) {
        isAutoGenerated = false;
        return envToken;
    }

    const generated = generateToken();
    isAutoGenerated = true;
    console.log(`[AUTH] No AUTH_TOKEN configured. Generated token: ${generated}. Set ICE_AUTH_TOKEN env var to use your own.`);

    // Best-effort: save generated token to config.json so it persists across restarts
    saveTokenToConfig(generated);

    return generated;
}

/**
 * Return whether the current token was auto-generated.
 */
export function isTokenAutoGenerated(): boolean {
    return isAutoGenerated;
}

/**
 * Create Bearer token auth middleware.
 * Always enforces auth. Localhost exemption is opt-in via `skipLocalhost` config.
 */
export function createBearerAuthMiddleware(config: AuthMiddlewareConfig) {
    const token = getAuthToken(config.token);
    const skipLocalhost = config.skipLocalhost === true;

    if (skipLocalhost) {
        console.log('[AUTH] WARNING: localhost exemption is ENABLED. Do NOT use this in production with FRP!');
    }

    return (req: Request, res: Response, next: NextFunction): void => {
        // Opt-in localhost exemption (unsafe with FRP TCP forwarding)
        if (skipLocalhost && isLocalhost(req)) {
            next();
            return;
        }

        const authHeader = req.headers.authorization;
        if (!authHeader || !authHeader.startsWith('Bearer ')) {
            res.status(401).json({ error: '未提供认证令牌', code: 'UNAUTHORIZED' });
            return;
        }

        const providedToken = authHeader.slice(7);
        if (providedToken !== token) {
            res.status(401).json({ error: '认证令牌无效', code: 'INVALID_TOKEN' });
            return;
        }

        next();
    };
}
