/**
 * ice-bubble Admin API
 *
 * ice-bubble 管理后台 API 服务入口
 */

import express from 'express';
import { config } from 'dotenv';
import { readFileSync, existsSync, mkdirSync } from 'fs';
import { join } from 'path';
import { logger } from './utils/index.js';
import { ModuleScheduler } from './modules/module-scheduler.js';
import { createModulesRouter } from './api/modules.js';
import { createDataRouter } from './api/data.js';
import { DBManager } from './storage/db-manager.js';
import { ModuleRepository } from './storage/module-repository.js';
import { DataRepository } from './storage/data-repository.js';
import { createResourcesRouter } from './api/resources.js';
import { createSubagentTasksRouter } from './api/tasks.js';
import { DataSync } from './data/data-sync.js';
import { AgentOverviewService } from './data/agent-overview.js';
import { CollectorClient } from './data/collector-client.js';
import { createBearerAuthMiddleware, getAuthToken, isTokenAutoGenerated } from './utils/auth-middleware.js';
import { GatewayConnection } from './server/gateway/connection.js';
import { GatewayRpc } from './server/gateway/rpc.js';
import { SSEManager } from './server/chat/sse-manager.js';

import { ChatController } from './server/chat/controller.js';
import { GatewayProxy } from './gateway/index.js';
import { GatewayWsServer } from './gateway/ws-server.js';
import { createChatProxyRouter, createSessionProxyRouter } from './api/chat-proxy.js';
import { createSessionsUnifiedRouter } from './api/sessions-unified.js';
import { createSessionGroupsRouter } from './api/session-groups.js';
import { createSessionPreferencesRouter } from './api/session-preferences.js';
import { createWorkspaceRouter } from './api/workspace.js';
import { createSettingsRouter } from './api/settings.js';

// 加载环境变量
config();

/**
 * 模块版本信息 - 从根 package.json 动态读取
 */
import { readFileSync as _readFileSync } from 'fs';
import { join as _join } from 'path';
const _rootPkg = JSON.parse(_readFileSync(_join(__dirname, '..', '..', 'package.json'), 'utf-8'));
export const VERSION: string = _rootPkg.version;

// 读取配置 - 使用相对路径
const configPath = './config/config.json';

interface ServerConfig {
  port?: number;
  host?: string;
}

interface ModuleConfig {
  moduleKey: string;
  name: string;
  baseUrl: string;
  enabled: boolean;
  pollInterval?: number;
}

interface DataSyncConfig {
  collectorBaseUrl?: string;
  moduleKey?: string;
  pollInterval?: number;
  batchSize?: number;
}

interface GatewayConfig {
  url?: string;
  token?: string;
}

interface AppConfig {
  server?: ServerConfig;
  modules?: ModuleConfig[];
  dataSync?: DataSyncConfig;
  auth?: { token?: string };
  gateway?: GatewayConfig;
}

let configData: AppConfig;
try {
  configData = JSON.parse(readFileSync(configPath, 'utf-8')) as AppConfig;
} catch (err) {
  const msg = err instanceof Error ? err.message : String(err);
  console.error(`[index] Failed to parse ${configPath}: ${msg}`);
  process.exit(1);
}

/**
 * 启动时自动加载模块
 * 从 config.json 读取模块配置，尝试连接并注册模块
 */
async function bootstrapModules(
  scheduler: ModuleScheduler,
  repository: ModuleRepository,
  moduleConfigs: Array<{ moduleKey: string; name: string; baseUrl: string; enabled: boolean; pollInterval?: number }>
): Promise<void> {
  const configs = moduleConfigs.filter(c => c.enabled);
  logger.info(`[Admin] 准备加载 ${configs.length} 个模块...`);

  for (const cfg of configs) {
    try {
      // 1. 检查模块是否已存在，存在则不更新注册时间
      const existingCreatedAt = await repository.getModuleCreatedAt(cfg.moduleKey);
      if (!existingCreatedAt) {
        await repository.registerModule({
          moduleKey: cfg.moduleKey,
          moduleName: cfg.name,
          moduleType: 'collector',
          status: 'running',
          version: 'unknown'
        });
      }

      // 2. 尝试获取状态
      const status = await scheduler.pollModuleNow(cfg.moduleKey);

      // 3. 保存状态
      if (status) {
        await repository.saveModuleStatus(cfg.moduleKey, status);
      }

      logger.info(`[Admin] 模块 ${cfg.moduleKey} 加载成功`);
    } catch (error) {
      logger.error(`[Admin] Module ${cfg.moduleKey} load failed`, { error });

      // 即使失败也注册
      await repository.registerModule({
        moduleKey: cfg.moduleKey,
        moduleName: cfg.name,
        moduleType: 'collector',
        status: 'error',
        version: 'unknown'
      });
    }
  }

  logger.info(`[Admin] 模块加载完成，共 ${configs.length} 个模块`);
}

/**
 * 启动管理后台服务
 */
export async function startAdmin(): Promise<void> {
    const app = express();
    app.use(express.json());

    // CORS middleware — 允许外部访问（开发/内网阶段）
    app.use((_req, res, next) => {
      res.setHeader('Access-Control-Allow-Origin', '*');
      res.setHeader('Access-Control-Allow-Methods', 'GET,POST,PUT,DELETE,OPTIONS');
      res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');
      if (_req.method === 'OPTIONS') {
        res.status(200).end();
        return;
      }
      next();
    });

    // Resolve auth token ONCE — avoid multiple getAuthToken() calls generating different tokens
    const authToken = getAuthToken(configData.auth?.token);

    // Auth status endpoint — no auth required (must be registered before auth middleware)
    // Desktop uses this to discover the auth requirements of this Admin instance.
    app.get('/api/auth/status', (_req, res) => {
        const configured = !!(process.env.ICE_AUTH_TOKEN || configData.auth?.token);
        const needsToken = isTokenAutoGenerated();
        res.json({
            configured,
            needsToken,
            tokenHint: needsToken
                ? 'Token was auto-generated. Set auth.token in config.json or ICE_AUTH_TOKEN env var to use a fixed value.'
                : undefined,
        });
    });

    // Token verification endpoint — no auth required (before auth middleware)
    // Desktop uses this to validate a token without accessing protected resources.
    app.post('/api/auth/verify', (req, res) => {
        const authHeader = req.headers.authorization;
        if (!authHeader || !authHeader.startsWith('Bearer ')) {
            res.status(401).json({ valid: false, error: '未提供认证令牌' });
            return;
        }
        const provided = authHeader.slice(7);
        if (provided !== authToken) {
            res.status(401).json({ valid: false, error: '认证令牌无效' });
            return;
        }
        res.json({ valid: true });
    });

    // Avatar endpoint — no auth required (browser <img> tags cannot send Authorization header)
    const avatarsDirEarly = process.env.ADMIN_AVATARS_DIR || join(__dirname, '..', '..', 'data', 'avatars');
    if (!existsSync(avatarsDirEarly)) {
 mkdirSync(avatarsDirEarly, { recursive: true });
    }
    app.get('/api/resources/avatars/:filename', (req, res) => {
      const filePath = join(avatarsDirEarly, req.params.filename);
      if (!existsSync(filePath)) {
        res.status(404).json({ error: 'Avatar not found' });
        return;
      }
      const ext = req.params.filename.split('.').pop()?.toLowerCase();
      const mimeMap: Record<string, string> = { png: 'image/png', jpg: 'image/jpeg', jpeg: 'image/jpeg', gif: 'image/gif', webp: 'image/webp', svg: 'image/svg+xml' };
      res.setHeader('Content-Type', mimeMap[ext || ''] || 'application/octet-stream');
      res.setHeader('Cache-Control', 'public, max-age=86400');
      res.sendFile(filePath);
    });

    // Bearer token auth middleware for all /api/* routes
    // Auth is always enforced for every request to /api/* regardless of source IP.
    app.use('/api', createBearerAuthMiddleware(authToken));

    const PORT = configData.server?.port || 13000;
    const HOST = configData.server?.host || '0.0.0.0';

    // 初始化数据库
    const dbPath = process.env.ADMIN_DB_PATH || join(__dirname, '..', '..', 'data', 'admin.db');
    const dbManager = new DBManager();
    await dbManager.init({ dbPath });
    await dbManager.migrate(21);  // 执行数据库迁移（v21: 会话偏好表）
    const repository = new ModuleRepository(dbManager.getConnection());
    logger.info('[Admin] 数据库初始化完成');

    // 首次启动检查：如果数据库中没有模块，自动注册 admin 自己
    const existingModules = await repository.getModules({ limit: 1 });
    if (existingModules.modules.length === 0) {
      await repository.registerModule({
        moduleKey: 'admin',
        moduleName: 'Admin 管理后台',
        moduleType: 'admin',
        status: 'running',
        version: VERSION
      });
      logger.info('[Admin] 首次启动，自动注册 admin 模块到数据库');
    }

    // 初始化模块调度器
    const moduleConfigs = configData.modules || [];
    const scheduler = new ModuleScheduler(moduleConfigs, logger, repository);

    logger.info('[Admin] 模块调度器初始化完成');
    logger.info(`[Admin] 已配置 ${moduleConfigs.length} 个模块`);

    // 初始化数据仓库和同步调度器
    const avatarsDir = avatarsDirEarly; // already created above before auth middleware
    const dataRepository = new DataRepository(dbManager.getConnection(), avatarsDir);
    const dataSyncConfig = configData.dataSync || {};
    const dataSync = new DataSync(
      {
        collectorBaseUrl: dataSyncConfig.collectorBaseUrl || 'http://localhost:13100',
        moduleKey: dataSyncConfig.moduleKey || 'collector-openclaw',
        pollInterval: dataSyncConfig.pollInterval || 60000,
        batchSize: dataSyncConfig.batchSize || 500,
      },
      dataRepository
    );
    dataSync.start();
    logger.info('[Admin] 数据同步调度器初始化完成');

    // 启动每日归档调度器（凌晨 3 点执行，保留 30 天数据）
    dataRepository.startArchiveScheduler(30, (count) => {
      logger.info(`[Admin] 归档任务完成，共归档 ${count} 条消息`);
    });
    logger.info('[Admin] 数据归档调度器已启动');

    // ── GatewayProxy (初始化提前，供后续路由使用) ──
    let gatewayProxy: GatewayProxy | null = null;
    try {
        gatewayProxy = new GatewayProxy();
        await gatewayProxy.connect();
        logger.info('[Admin] GatewayProxy connected');
    } catch (err) {
        logger.warn('[Admin] GatewayProxy connection failed (non-fatal)', {
            error: err instanceof Error ? err.message : String(err),
        });
    }

    // 注册 API 路由
    // IMPORTANT: Unified sessions route must be BEFORE data router,
    // because data router's /sessions/:key would match /sessions/unified
    if (gatewayProxy) {
        app.use('/api', createSessionsUnifiedRouter({ proxy: gatewayProxy, repository: dataRepository }));
    }
    app.use('/api', createDataRouter({
      repository: dataRepository,
      db: dbManager.getConnection(),
      agentOverviewService: new AgentOverviewService(
        dataRepository,
        new CollectorClient({ baseUrl: dataSyncConfig.collectorBaseUrl || 'http://localhost:13100' })
      ),
      gatewayProxy,
    }));
    app.use('/api/modules', createModulesRouter(scheduler));
    app.use('/api/resources', createResourcesRouter(dataRepository));
    app.use('/api/subagent-tasks', createSubagentTasksRouter({ db: dbManager.getConnection() }));
    // Session groups + create session (must be BEFORE data router to avoid /sessions/:key conflict)
    app.use('/api', createSessionGroupsRouter({ db: dbManager.getConnection(), gatewayProxy }));
    app.use('/api', createSessionPreferencesRouter({ db: dbManager.getConnection() }));
    app.use('/api', createWorkspaceRouter());
    app.use('/api', createSettingsRouter());

    // ── Chat Gateway Integration (B7) ──
    // NOTE: 这里创建的 GatewayConnection/GatewayRpc 用于 SSE 聊天推送（浏览器直连 Admin）。
    // 上方的 GatewayProxy 用于 WebSocket 代理转发 Desktop 请求到 Gateway。
    // 两者协议不同（SSE vs WS），用途不同，非重复连接。Token 统一使用 GatewayProxy 的来源。
    const gwConfig = configData.gateway || {};
    const gatewayUrl = gwConfig.url || 'ws://127.0.0.1:18789';
    // 复用 GatewayProxy 的 token 获取逻辑（OpenClaw config > env var > fallback）
    // 避免 configData.gateway.token 与 GatewayProxy 的 token 来源不一致
    const gatewayToken = gwConfig.token || process.env.GATEWAY_AUTH_TOKEN || '';
    const gatewayConn = new GatewayConnection(gatewayUrl, gatewayToken);
    const gatewayRpc = new GatewayRpc(gatewayConn);
    const sseManager = new SSEManager(gatewayRpc);
    const chatController = new ChatController(gatewayRpc, sseManager);

    // Sessions API: handled by createDataRouter in data.ts

    app.get('/api/sessions/:key/messages', (req, res) => {
      const limit = parseInt(req.query.limit as string, 10) || 50;
      const offset = parseInt(req.query.offset as string, 10) || 0;
      const result = dataRepository.getMessages({ session_key: req.params.key, limit, offset });
      // 从 session_key 提取 agent_id，补充头像和名称
      const agentId = req.params.key.split(':')[1] || '';
      const agentInfo = (() => {
        const agents = dataRepository.getAgents();
        const a = agents.find(ag => ag.agent_id === agentId);
        return { name: a?.agent_name ?? null, avatar: a?.avatar ?? null };
      })();
      const messages = result.messages.map((m) => ({
        id: String(m.id ?? m.source_id ?? ''),
        session_key: m.session_key,
        role: m.message_type === 'agent' ? 'assistant' : (m.message_type ?? 'user'),
        content: m.content ?? '',
        created_at: m.created_at,
        model: m.model ?? null,
        agent_id: agentId,
        agent_name: agentInfo.name,
        avatar: agentInfo.avatar,
        // 透传原始字段，供前端过滤
        message_type: m.message_type,
        is_system_context: m.is_system_context ?? 0,
      }));
      res.json({ messages, total: result.total });
    });

    // Chat routes
    app.post('/api/chat/send', (req, res) => chatController.send(req, res));
    app.post('/api/chat/abort', (req, res) => chatController.abort(req, res));
    app.get('/api/chat/stream', (req, res) => chatController.stream(req, res));

    // HTTP proxy routes (via GatewayProxy)
    if (gatewayProxy) {
        app.use('/api/chat', createChatProxyRouter(gatewayProxy));
        app.use('/api/gateway', createSessionProxyRouter(gatewayProxy));
        logger.info('[Admin] GatewayProxy HTTP routes registered');
    }

    // Connect to Gateway in background — failure should NOT crash the server
    gatewayConn.connect().catch((err) => {
        logger.warn('[Admin] Gateway connection failed (will auto-retry)', {
            error: err instanceof Error ? err.message : String(err),
            url: gatewayUrl,
        });
    });

    gatewayConn.on('reconnect', () => {
        logger.info('[Admin] Gateway reconnecting...', { url: gatewayUrl });
        sseManager.broadcastAll('status', { connected: false });
    });

    gatewayConn.on('disconnect', () => {
        logger.warn('[Admin] Gateway disconnected');
        sseManager.broadcastAll('status', { connected: false });
    });

    // 健康检查
    app.get('/health', (_req, res) => {
        res.json({ status: 'ok', version: VERSION });
    });

    // 启动调度器
    scheduler.start();

    // 启动后，加载配置中的模块
    await bootstrapModules(scheduler, repository, moduleConfigs);

    // 启动服务器
    const httpServer = app.listen(PORT, HOST, () => {
        logger.info(`[Admin] 服务启动成功: http://${HOST}:${PORT}`);
        logger.info(`[Admin] API: http://${HOST}:${PORT}/api/modules`);
    });

    // 挂载 WebSocket 服务器到 /ws（通过 GatewayProxy）
    if (gatewayProxy) {
        try {
            const wsServer = new GatewayWsServer(gatewayProxy, authToken);
            wsServer.start(httpServer);
            logger.info('[Admin] WebSocket server started on /ws');
        } catch (err) {
            logger.warn('[Admin] WebSocket server failed to start', {
                error: err instanceof Error ? err.message : String(err),
            });
        }
    }
}

startAdmin().catch((error) => {
    logger.error('Failed to start admin', { error });
    process.exit(1);
});
