/**
 * ice-bubble Admin API
 *
 * ice-bubble 管理后台 API 服务入口
 */

import express from 'express';
import { config } from 'dotenv';
import { readFileSync, existsSync, mkdirSync } from 'fs';
import { join } from 'path';
import rateLimit from 'express-rate-limit';
import { logger } from './utils/index.js';
import { ModuleScheduler } from './modules/module-scheduler.js';
import { createModulesRouter } from './api/modules.js';
import { createDataRouter } from './api/data.js';
import { DBManager } from './storage/db-manager.js';
import { ModuleRepository } from './storage/module-repository.js';
import { DataRepository } from './storage/data-repository.js';
import { createResourcesRouter } from './api/resources.js';
import { createSubagentTasksRouter } from './api/tasks.js';
import { DataSync } from './data/data-sync.js';
import { AgentOverviewService } from './data/agent-overview.js';
import { CollectorClient } from './data/collector-client.js';
import { createBearerAuthMiddleware, getAuthToken, isTokenAutoGenerated } from './utils/auth-middleware.js';
import { GatewayRpc } from './server/gateway/rpc.js';
import { SSEManager } from './server/chat/sse-manager.js';

import { ChatController } from './server/chat/controller.js';
import { AttachmentStorage } from './server/chat/attachment-storage.js';
import { OpenCodeHttpClient } from './server/chat/opencode-client.js';
import { createOpenCodeChatRouter } from './api/opencode-chat.js';
import { GatewayProxy } from './gateway/index.js';
import { GatewayWsServer } from './gateway/ws-server.js';
import { createChatProxyRouter, createSessionProxyRouter } from './api/chat-proxy.js';
import { createSessionsUnifiedRouter } from './api/sessions-unified.js';
import { createSessionGroupsRouter } from './api/session-groups.js';
import { createSessionPreferencesRouter } from './api/session-preferences.js';
import { createWorkspaceRouter } from './api/workspace.js';
import { createSettingsRouter } from './api/settings.js';
import { createMediaRouter, createMediaFileRouter } from './api/media.js';
import { createHealthRouter } from './api/health.js';

// 加载环境变量
config();

/**
 * 模块版本信息 - 从根 package.json 动态读取
 */
import { readFileSync as _readFileSync } from 'fs';
import { join as _join } from 'path';
const _rootPkg = JSON.parse(_readFileSync(_join(__dirname, '..', '..', 'package.json'), 'utf-8'));
export const VERSION: string = _rootPkg.version;

// 读取配置 - 使用相对路径
const configPath = './config/config.json';

interface ServerConfig {
  port?: number;
  host?: string;
}

interface ModuleConfig {
  moduleKey: string;
  name: string;
  baseUrl: string;
  enabled: boolean;
  pollInterval?: number;
  /** 当模块为 collector 类型时，配置数据同步参数 */
  sync?: {
    enabled?: boolean;
    pollInterval?: number;
    batchSize?: number;
  };
}

interface DataSyncConfig {
  collectorBaseUrl?: string;
  moduleKey?: string;
  platform?: string;
  pollInterval?: number;
  batchSize?: number;
}

interface DataSyncOpencodeConfig {
  collectorBaseUrl?: string;
  moduleKey?: string;
  pollInterval?: number;
  batchSize?: number;
}

interface GatewayConfig {
  url?: string;
  token?: string;
}

interface CorsConfig {
  enabled?: boolean;
  origins?: string[];
}

interface OpenCodeConfig {
  serveUrl?: string;
  enabled?: boolean;
}

interface AppConfig {
  server?: ServerConfig;
  modules?: ModuleConfig[];
  dataSync?: DataSyncConfig;
  dataSyncOpencode?: DataSyncOpencodeConfig;
  auth?: { token?: string };
  gateway?: GatewayConfig;
  cors?: CorsConfig;
  opencode?: OpenCodeConfig;
}

let configData: AppConfig;
try {
  configData = JSON.parse(readFileSync(configPath, 'utf-8')) as AppConfig;
} catch (err) {
  const msg = err instanceof Error ? err.message : String(err);
  console.error(`[index] Failed to parse ${configPath}: ${msg}`);
  process.exit(1);
}

/**
 * 启动时自动加载模块
 * 从 config.json 读取模块配置，尝试连接并注册模块
 */
async function bootstrapModules(
  scheduler: ModuleScheduler,
  repository: ModuleRepository,
  moduleConfigs: Array<{ moduleKey: string; name: string; baseUrl: string; enabled: boolean; pollInterval?: number }>
): Promise<void> {
  const configs = moduleConfigs.filter(c => c.enabled);
  logger.info(`[Admin] 准备加载 ${configs.length} 个模块...`);

  for (const cfg of configs) {
    try {
      // 1. 检查模块是否已存在，存在则不更新注册时间
      const existingCreatedAt = await repository.getModuleCreatedAt(cfg.moduleKey);
      if (!existingCreatedAt) {
        await repository.registerModule({
          moduleKey: cfg.moduleKey,
          moduleName: cfg.name,
          moduleType: 'collector',
          status: 'running',
          version: 'unknown'
        });
      }

      // 2. 尝试获取状态
      const status = await scheduler.pollModuleNow(cfg.moduleKey);

      // 3. 保存状态
      if (status) {
        await repository.saveModuleStatus(cfg.moduleKey, status);
      }

      logger.info(`[Admin] 模块 ${cfg.moduleKey} 加载成功`);
    } catch (error) {
      logger.error(`[Admin] Module ${cfg.moduleKey} load failed`, { error });

      // 即使失败也注册
      await repository.registerModule({
        moduleKey: cfg.moduleKey,
        moduleName: cfg.name,
        moduleType: 'collector',
        status: 'error',
        version: 'unknown'
      });
    }
  }

  logger.info(`[Admin] 模块加载完成，共 ${configs.length} 个模块`);
}

/**
 * 启动管理后台服务
 */
export async function startAdmin(): Promise<void> {
    const app = express();
    app.use(express.json({ limit: '10mb' }));
    app.use(express.urlencoded({ limit: '10mb', extended: true }));

    // CORS middleware — 基于配置收紧 origin
    const corsOrigins = configData.cors?.origins;
    const corsOriginAllowed = corsOrigins && corsOrigins.length > 0;
    app.use((req, res, next) => {
      if (corsOriginAllowed && corsOrigins) {
        const origin = req.headers.origin;
        if (origin && corsOrigins.includes(origin)) {
          res.setHeader('Access-Control-Allow-Origin', origin);
        }
      } else {
        res.setHeader('Access-Control-Allow-Origin', '*');
      }
      res.setHeader('Access-Control-Allow-Methods', 'GET,POST,PUT,DELETE,OPTIONS');
      res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');
      if (req.method === 'OPTIONS') {
        res.status(200).end();
        return;
      }
      next();
    });

    // 速率限制：未认证请求 60 req/min per IP
    const getClientIp = (req: express.Request): string => {
      return (req.headers['x-forwarded-for'] as string)?.split(',')[0]?.trim() || req.ip || 'unknown';
    };
    const unauthLimiter = rateLimit({
      windowMs: 60 * 1000,
      max: 60,
      keyGenerator: (req) => getClientIp(req),
      handler: (_req, res) => {
        res.setHeader('Retry-After', '60');
        res.status(429).json({ error: 'Too Many Requests' });
      },
    });
    // 速率限制：已认证请求 300 req/min per token
    const authLimiter = rateLimit({
      windowMs: 60 * 1000,
      max: 300,
      keyGenerator: (req) => {
        const authHeader = req.headers.authorization;
        if (authHeader?.startsWith('Bearer ')) {
          return `token:${authHeader.slice(7)}`;
        }
        return getClientIp(req);
      },
      skip: (req) => {
        // 仅对无 Bearer Token 的请求跳过（由 unauthLimiter 处理）
        return !req.headers.authorization?.startsWith('Bearer ');
      },
      handler: (_req, res) => {
        res.setHeader('Retry-After', '60');
        res.status(429).json({ error: 'Too Many Requests' });
      },
    });
    app.use(unauthLimiter);
    app.use(authLimiter);

    // Resolve auth token ONCE — avoid multiple getAuthToken() calls generating different tokens
    const authToken = getAuthToken(configData.auth?.token);

    // Auth status endpoint — no auth required (must be registered before auth middleware)
    // Desktop uses this to discover the auth requirements of this Admin instance.
    app.get('/api/auth/status', (_req, res) => {
        const configured = !!(process.env.ICE_AUTH_TOKEN || configData.auth?.token);
        const needsToken = isTokenAutoGenerated();
        res.json({
            configured,
            needsToken,
            tokenHint: needsToken
                ? 'Token was auto-generated. Set auth.token in config.json or ICE_AUTH_TOKEN env var to use a fixed value.'
                : undefined,
        });
    });

    // Token verification endpoint — no auth required (before auth middleware)
    // Desktop uses this to validate a token without accessing protected resources.
    app.post('/api/auth/verify', (req, res) => {
        const authHeader = req.headers.authorization;
        if (!authHeader || !authHeader.startsWith('Bearer ')) {
            res.status(401).json({ valid: false, error: '未提供认证令牌' });
            return;
        }
        const provided = authHeader.slice(7);
        if (provided !== authToken) {
            res.status(401).json({ valid: false, error: '认证令牌无效' });
            return;
        }
        res.json({ valid: true });
    });

    // Avatar endpoint — no auth required (browser <img> tags cannot send Authorization header)
    // Uses path safety checks (rejects '..' and '/') to prevent path traversal.
    const avatarsDirEarly = process.env.ADMIN_AVATARS_DIR || join(__dirname, '..', '..', 'data', 'avatars');
    if (!existsSync(avatarsDirEarly)) {
 mkdirSync(avatarsDirEarly, { recursive: true });
    }
    app.get('/api/resources/avatars/:filename', (req, res) => {
      const { filename } = req.params;
      if (!filename || filename.includes('..') || filename.includes('/')) {
        res.status(404).json({ error: 'Avatar not found' });
        return;
      }
      const filePath = join(avatarsDirEarly, filename);
      if (!existsSync(filePath)) {
        res.status(404).json({ error: 'Avatar not found' });
        return;
      }
      const ext = filename.split('.').pop()?.toLowerCase();
      const mimeMap: Record<string, string> = { png: 'image/png', jpg: 'image/jpeg', jpeg: 'image/jpeg', gif: 'image/gif', webp: 'image/webp', svg: 'image/svg+xml' };
      res.setHeader('Content-Type', mimeMap[ext || ''] || 'application/octet-stream');
      res.setHeader('Cache-Control', 'public, max-age=86400');
      res.sendFile(filePath);
    });

    // Attachment query API — before auth middleware (Desktop uses request() but we register here to avoid :filename collision)
    // Actual handler is registered below after attachmentStorage is initialized; for now use a placeholder
    let attachmentQueryHandler: ((req: any, res: any) => void) | null = null;
    app.get('/api/attachments/query', (req, res) => {
      if (attachmentQueryHandler) { attachmentQueryHandler(req, res); return; }
      res.status(503).json({ attachments: [] });
    });

    // Attachment static files — no auth required (browser <img> tags cannot send Authorization header)
    const attachmentsDirEarly = process.env.ATTACHMENTS_DIR || join(process.env.HOME || '/root', '.local', 'share', 'ice-bubble', 'data', 'attachments');
    if (!existsSync(attachmentsDirEarly)) {
      mkdirSync(attachmentsDirEarly, { recursive: true });
    }
    app.get('/api/attachments/:filename', (req, res) => {
      const { filename } = req.params;
      if (!filename || filename.includes('..') || filename.includes('/') || filename === 'query') {
        res.status(404).json({ error: 'Attachment not found' });
        return;
      }
      const filePath = join(attachmentsDirEarly, filename);
      if (!existsSync(filePath)) {
        res.status(404).json({ error: 'Attachment not found' });
        return;
      }
      const ext = filename.split('.').pop()?.toLowerCase();
      const mimeMap: Record<string, string> = { png: 'image/png', jpg: 'image/jpeg', jpeg: 'image/jpeg', gif: 'image/gif', webp: 'image/webp', svg: 'image/svg+xml' };
      res.setHeader('Content-Type', mimeMap[ext || ''] || 'application/octet-stream');
      res.setHeader('Cache-Control', 'public, max-age=604800');
      res.sendFile(filePath);
    });

    // Media file download — no auth required (browser <img> tags cannot send Authorization header)
    // Placeholder: actual router registered after DB init
    let mediaFileHandler: ((req: any, res: any) => void) | null = null;
    app.get('/api/media/file/:id', (req, res) => {
      if (mediaFileHandler) { mediaFileHandler(req, res); return; }
      res.status(503).json({ error: 'Media service not ready' });
    });

    // Bearer token auth middleware for all /api/* routes
    // Auth is always enforced for every request to /api/* regardless of source IP.
    // Note: /api/resources/avatars and /api/attachments are registered before this middleware
    // because browser <img> tags cannot send Authorization header.
    app.use('/api', createBearerAuthMiddleware(authToken));

    const PORT = configData.server?.port || 13000;
    const HOST = configData.server?.host || '0.0.0.0';

    // 初始化数据库
    const dbPath = process.env.ADMIN_DB_PATH || join(__dirname, '..', '..', 'data', 'admin.db');
    const dbManager = new DBManager();
    await dbManager.init({ dbPath });
    await dbManager.migrate(25);  // 执行数据库迁移（v25: platform 多平台支持）
    const repository = new ModuleRepository(dbManager.getConnection());
    logger.info('[Admin] 数据库初始化完成');

    // 首次启动检查：如果数据库中没有模块，自动注册 admin 自己
    const existingModules = await repository.getModules({ limit: 1 });
    if (existingModules.modules.length === 0) {
      await repository.registerModule({
        moduleKey: 'admin',
        moduleName: 'Admin 管理后台',
        moduleType: 'admin',
        status: 'running',
        version: VERSION
      });
      logger.info('[Admin] 首次启动，自动注册 admin 模块到数据库');
    }

    // 初始化模块调度器
    const moduleConfigs = configData.modules || [];
    const scheduler = new ModuleScheduler(moduleConfigs, logger, repository);

    logger.info('[Admin] 模块调度器初始化完成');
    logger.info(`[Admin] 已配置 ${moduleConfigs.length} 个模块`);

    // 初始化数据仓库和同步调度器
    const dataRepository = new DataRepository(dbManager.getConnection(), avatarsDirEarly);

    // 初始化附件存储
    const attachmentsDir = process.env.ATTACHMENTS_DIR || join(process.env.HOME || '/root', '.local', 'share', 'ice-bubble', 'data', 'attachments');
    const attachmentStorage = new AttachmentStorage(attachmentsDir, dbManager.getConnection());
    logger.info('[Admin] Attachment storage initialized', { dir: attachmentsDir });

    // ── 配置驱动的数据同步：从 modules 自动发现 collector 并创建 DataSync ──
    const dataSyncs: DataSync[] = [];
    const createdModuleKeys = new Set<string>();
    const legacyDataSyncConfigs = new Map<string, { collectorBaseUrl: string; moduleKey: string; platform: string; pollInterval: number; batchSize: number }>();

    // 1. 收集 legacy 配置作为 fallback
    if (configData.dataSync) {
      const ds = configData.dataSync;
      legacyDataSyncConfigs.set(ds.moduleKey || 'collector-openclaw', {
        collectorBaseUrl: ds.collectorBaseUrl || 'http://localhost:13100',
        moduleKey: ds.moduleKey || 'collector-openclaw',
        platform: 'openclaw',
        pollInterval: ds.pollInterval || 60000,
        batchSize: ds.batchSize || 500,
      });
    }
    if (configData.dataSyncOpencode) {
      const ds = configData.dataSyncOpencode;
      legacyDataSyncConfigs.set(ds.moduleKey || 'collector-opencode', {
        collectorBaseUrl: ds.collectorBaseUrl || 'http://localhost:13101',
        moduleKey: ds.moduleKey || 'collector-opencode',
        platform: 'opencode',
        pollInterval: ds.pollInterval || 30000,
        batchSize: ds.batchSize || 500,
      });
    }

    // 2. 遍历 modules，优先使用 sync 字段，fallback 到 legacy 配置
    for (const mod of moduleConfigs) {
      if (!mod.enabled || !mod.baseUrl) continue;
      // 非 collector 类型模块跳过（moduleKey 以 collector- 开头或 sync 字段存在）
      if (!mod.moduleKey.startsWith('collector-') && !mod.sync) continue;

      let syncConfig: { collectorBaseUrl: string; moduleKey: string; platform: string; pollInterval: number; batchSize: number };

      if (mod.sync) {
        // 新配置路径：从 module 的 sync 字段读取
        if (mod.sync.enabled === false) continue;
        const platform = mod.moduleKey.replace(/^collector-/, '');
        syncConfig = {
          collectorBaseUrl: mod.baseUrl,
          moduleKey: mod.moduleKey,
          platform,
          pollInterval: mod.sync.pollInterval || 30000,
          batchSize: mod.sync.batchSize || 500,
        };
      } else {
        // Fallback：从 legacy 配置匹配
        const legacy = legacyDataSyncConfigs.get(mod.moduleKey);
        if (!legacy) continue;
        syncConfig = legacy;
      }

      const sync = new DataSync(syncConfig, dataRepository);
      sync.start();
      dataSyncs.push(sync);
      createdModuleKeys.add(syncConfig.moduleKey);
      logger.info(`[Admin] 数据同步调度器初始化完成 (${syncConfig.platform})`);
    }

    // 3. 兜底：如果 modules 中没有匹配到 legacy 配置，直接创建
    for (const [key, syncConfig] of legacyDataSyncConfigs) {
      if (createdModuleKeys.has(key)) continue;
      const sync = new DataSync(syncConfig, dataRepository);
      sync.start();
      dataSyncs.push(sync);
      createdModuleKeys.add(key);
      logger.info(`[Admin] 数据同步调度器初始化完成 (${syncConfig.platform}, legacy)`);
    }

    // 启动每日归档调度器（凌晨 3 点执行，保留 30 天数据）
    dataRepository.startArchiveScheduler(30, (count) => {
      logger.info(`[Admin] 归档任务完成，共归档 ${count} 条消息`);
    });
    logger.info('[Admin] 数据归档调度器已启动');

    // ── GatewayProxy (初始化提前，供后续路由使用) ──
    let gatewayProxy: GatewayProxy | null = null;
    try {
        gatewayProxy = new GatewayProxy();
        await gatewayProxy.connect();
        logger.info('[Admin] GatewayProxy connected');
    } catch (err) {
        logger.warn('[Admin] GatewayProxy connection failed (non-fatal)', {
            error: err instanceof Error ? err.message : String(err),
        });
    }

    // ── OpenCode Chat Client ──
    const opencodeConfig = configData.opencode;
    let opencodeClient: OpenCodeHttpClient | null = null;
    if (opencodeConfig?.enabled !== false) {
      const serveUrl = opencodeConfig?.serveUrl || 'http://localhost:4097';
      opencodeClient = new OpenCodeHttpClient({ baseUrl: serveUrl });

      const healthy = await opencodeClient.healthCheck().catch(() => false);
      if (healthy) {
        logger.info(`[Admin] OpenCode client connected at ${serveUrl}`);
      } else {
        logger.warn(`[Admin] OpenCode is not reachable at ${serveUrl} — routes will still be registered`);
      }
    } else {
      logger.info('[Admin] OpenCode chat is disabled in config');
    }

    // 注册 API 路由
    // IMPORTANT: Unified sessions route must be BEFORE data router,
    // because data router's /sessions/:key would match /sessions/unified
    if (gatewayProxy) {
        app.use('/api', createSessionsUnifiedRouter({ proxy: gatewayProxy, repository: dataRepository }));
    }
    app.use('/api', createDataRouter({
      repository: dataRepository,
      db: dbManager.getConnection(),
      agentOverviewService: new AgentOverviewService(
        dataRepository,
        new CollectorClient({ baseUrl: moduleConfigs.find(m => m.moduleKey.startsWith('collector-') && m.enabled)?.baseUrl || 'http://localhost:13100' })
      ),
      gatewayProxy,
    }));
    app.use('/api/modules', createModulesRouter(scheduler));
    // Resources router — avatars handled above (before auth middleware), so no /avatars route here.
    app.use('/api/resources', createResourcesRouter(dataRepository));
    app.use('/api/subagent-tasks', createSubagentTasksRouter({ db: dbManager.getConnection() }));
    // Session groups + create session (must be BEFORE data router to avoid /sessions/:key conflict)
    app.use('/api', createSessionGroupsRouter({ db: dbManager.getConnection(), gatewayProxy }));
    app.use('/api', createSessionPreferencesRouter({ db: dbManager.getConnection() }));
    app.use('/api', createWorkspaceRouter());
    app.use('/api', createSettingsRouter());

    // OpenCode chat routes (if client is available)
    if (opencodeClient) {
      app.use('/api/opencode', createOpenCodeChatRouter(opencodeClient));
      logger.info('[Admin] OpenCode chat routes registered at /api/opencode');
    }

    // ── Chat Gateway Integration (B7) ──
    // Uses the same GatewayProxy as WebSocket proxy (single connection to Gateway).
    // GatewayRpc is a thin adapter that adds subscribe/event routing on top of GatewayProxy.
    let gatewayRpc: GatewayRpc | null = null;
    let sseManager: SSEManager | null = null;
    let chatController: ChatController | null = null;
    if (gatewayProxy) {
      gatewayRpc = new GatewayRpc(gatewayProxy);
      sseManager = new SSEManager(gatewayRpc);
      chatController = new ChatController(gatewayRpc, sseManager, attachmentStorage);
      logger.info('[Admin] GatewayRpc (chat SSE) initialized via GatewayProxy');
    } else {
      logger.warn('[Admin] No GatewayProxy — chat SSE will not be available');
    }

    // Sessions API: handled by createDataRouter in data.ts

    app.get('/api/sessions/:key/messages', (req, res) => {
      const limit = parseInt(req.query.limit as string, 10) || 50;
      const offset = parseInt(req.query.offset as string, 10) || 0;
      const result = dataRepository.getMessages({ session_key: req.params.key, limit, offset });
      // 从 session_key 提取 agent_id，补充头像和名称
      const agentId = req.params.key.split(':')[1] || '';
      const agentInfo = (() => {
        const agents = dataRepository.getAgents();
        const a = agents.find(ag => ag.agent_id === agentId);
        return { name: a?.agent_name ?? null, avatar: a?.avatar ?? null };
      })();
      const messages = result.messages.map((m) => ({
        id: String(m.id ?? m.source_id ?? ''),
        session_key: m.session_key,
        role: m.message_type === 'agent' ? 'assistant' : (m.message_type ?? 'user'),
        content: m.content ?? '',
        created_at: m.created_at,
        model: m.model ?? null,
        agent_id: agentId,
        agent_name: agentInfo.name,
        avatar: agentInfo.avatar,
        // 透传原始字段，供前端过滤
        message_type: m.message_type,
        is_system_context: m.is_system_context ?? 0,
      }));
      res.json({ messages, total: result.total });
    });

    // Media routes (after auth middleware — metadata queries are authenticated)
    const gatewayMediaDir = join(process.env.HOME || '/root', '.openclaw', 'media', 'inbound');
    const canvasDir = join(process.env.HOME || '/root', '.openclaw', 'canvas');
    const mediaMetaRouter = createMediaRouter({
      db: dbManager.getConnection(),
      attachmentsDir: attachmentsDir,
      gatewayProxy,
      gatewayMediaDir,
      canvasDir,
    });
    app.use('/api/media', mediaMetaRouter);

    // Wire up media file handler (registered before auth, now we have DB access)
    const mediaFileRouter = createMediaFileRouter({
      db: dbManager.getConnection(),
      attachmentsDir: attachmentsDir,
      gatewayProxy,
      gatewayMediaDir,
      canvasDir,
    });
    mediaFileHandler = (req, res) => mediaFileRouter(req, res, () => {});

    // Attachment query API — after auth middleware, Desktop uses authenticated request()
    // (handler placeholder was registered earlier before :filename route)
    attachmentQueryHandler = (req, res) => {
      const sessionKey = req.query.session_key as string;
      if (!sessionKey) { res.status(400).json({ attachments: [] }); return; }
      const attachments = attachmentStorage.getAttachments(sessionKey);
      res.json({ attachments });
    };

    // Chat routes (only if GatewayProxy is available)
    if (chatController) {
      app.post('/api/chat/send', (req, res) => chatController!.send(req, res));
      app.post('/api/chat/abort', (req, res) => chatController!.abort(req, res));
      app.get('/api/chat/stream', (req, res) => chatController!.stream(req, res));
    }

    // HTTP proxy routes (via GatewayProxy)
    if (gatewayProxy) {
        app.use('/api/chat', createChatProxyRouter(gatewayProxy));
        app.use('/api/gateway', createSessionProxyRouter(gatewayProxy));
        logger.info('[Admin] GatewayProxy HTTP routes registered');
    }

    // GatewayProxy handles its own reconnection logic.
    // Forward reconnect/disconnect events to SSE clients for status updates.
    if (gatewayProxy) {
      gatewayProxy.on('disconnected', () => {
        logger.warn('[Admin] Gateway disconnected');
        sseManager?.broadcastAll('status', { connected: false });
      });
      gatewayProxy.on('reconnecting', () => {
        logger.info('[Admin] Gateway reconnecting...');
        sseManager?.broadcastAll('status', { connected: false });
      });
      gatewayProxy.on('connected', () => {
        logger.info('[Admin] Gateway reconnected');
        sseManager?.broadcastAll('status', { connected: true });
      });
    }

    // 健康检查（在 auth middleware 之前，方便监控）
    app.use(createHealthRouter(dbManager.getConnection(), configData));

    // 启动调度器
    scheduler.start();

    // 启动后，加载配置中的模块
    await bootstrapModules(scheduler, repository, moduleConfigs);

    // 启动服务器
    const httpServer = app.listen(PORT, HOST, () => {
        logger.info(`[Admin] 服务启动成功: http://${HOST}:${PORT}`);
        logger.info(`[Admin] API: http://${HOST}:${PORT}/api/modules`);
    });

    // 挂载 WebSocket 服务器到 /ws（通过 GatewayProxy）
    if (gatewayProxy) {
        try {
            const wsServer = new GatewayWsServer(gatewayProxy, authToken, attachmentStorage);
            wsServer.start(httpServer);
            logger.info('[Admin] WebSocket server started on /ws');
        } catch (err) {
            logger.warn('[Admin] WebSocket server failed to start', {
                error: err instanceof Error ? err.message : String(err),
            });
        }
    }
}

startAdmin().catch((error) => {
    logger.error('Failed to start admin', { error });
    process.exit(1);
});
